--- #YAML:1.0
name:               OMA-Download-OTA
version:            1.00.06
abstract:           Perl extension for creating download descriptor objects according to the OMA Download OTA 1.0 specification.
author:
    - Bernard Nauwelaerts <bpgn@cpan.org>
license:            GPL_3
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
